version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./model weights:/app/model_weights
    environment:
      - FLASK_ENV=production
      - PORT=5000
    networks:
      - eleven11-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - eleven11-network
    restart: unless-stopped

networks:
  eleven11-network:
    driver: bridge

volumes:
  model_data:
